import { useState } from "react";
import { Download, FileText, File } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";
import { PHASE_LABELS, Phase } from "@/types/tasks";
import type { PhaseData } from "@/hooks/usePhaseSnapshot";

interface ExportSnapshotButtonProps {
  phases: PhaseData[];
  projectName?: string;
}

export function ExportSnapshotButton({ phases, projectName = "Project" }: ExportSnapshotButtonProps) {
  const [isExporting, setIsExporting] = useState(false);

  const generateTextContent = (): string => {
    const lines: string[] = [];
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    lines.push(`PHASE SNAPSHOT`);
    lines.push(`${projectName}`);
    lines.push(`Exported on ${date}`);
    lines.push(`${"═".repeat(50)}`);
    lines.push("");

    phases.forEach((phaseData) => {
      if (!phaseData.hasContent) return;

      const phaseLabel = PHASE_LABELS[phaseData.phase as Phase] || phaseData.phase;
      lines.push(`\n${"─".repeat(50)}`);
      lines.push(`${phaseLabel.toUpperCase()}`);
      lines.push(`${"─".repeat(50)}\n`);

      phaseData.blocks.forEach((block) => {
        lines.push(`▸ ${block.label}`);
        lines.push("");
        
        // Format based on content type
        const items = block.structuredContent?.items || [];
        
        switch (block.contentType) {
          case "numbered-list":
            items.forEach((item, idx) => {
              lines.push(`  ${idx + 1}. ${item.value}`);
            });
            break;
            
          case "key-value":
            items.forEach((item) => {
              lines.push(`  ${item.label}:`);
              lines.push(`    ${item.value}`);
            });
            break;
            
          case "offer-stack":
            items.forEach((item, idx) => {
              if (idx > 0) lines.push("");
              lines.push(`  ${item.label}`);
              if (item.value) lines.push(`  ${item.value}`);
              if (item.secondary) lines.push(`  ${item.secondary}`);
            });
            break;
            
          case "checklist":
            items.forEach((item) => {
              lines.push(`  ✓ ${item.value}`);
            });
            break;
            
          case "dates":
            items.forEach((item) => {
              lines.push(`  ${item.label}: ${item.value}`);
            });
            break;
            
          case "metrics":
            items.forEach((item) => {
              lines.push(`  ${item.label}: ${item.value}`);
            });
            break;
            
          case "quote":
            items.forEach((item) => {
              lines.push(`  "${item.value}"`);
            });
            break;
            
          case "social-bio":
            items.forEach((item, idx) => {
              if (idx > 0) lines.push("");
              lines.push(`  [${item.label}]`);
              lines.push(`  ${item.value}`);
            });
            break;
            
          case "visual-palette":
            const colors = items.filter(i => i.label === "color");
            const fonts = items.filter(i => i.label !== "color");
            if (colors.length > 0) {
              lines.push("  Colors:");
              colors.forEach((c) => {
                lines.push(`    • ${c.color || c.value}${c.value ? ` (${c.value})` : ""}`);
              });
            }
            if (fonts.length > 0) {
              lines.push("  Fonts:");
              fonts.forEach((f) => {
                lines.push(`    • ${f.label}: ${f.value}`);
              });
            }
            break;
            
          case "badge":
            items.forEach((item) => {
              lines.push(`  [${item.value}]`);
            });
            break;
            
          default:
            items.forEach((item) => {
              lines.push(`  ${item.value}`);
            });
        }
        
        lines.push("");
      });
    });

    lines.push(`\n${"═".repeat(50)}`);
    lines.push(`Generated by Launchbox`);

    return lines.join("\n");
  };

  const handleExportText = async () => {
    setIsExporting(true);
    try {
      const content = generateTextContent();
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `phase-snapshot-${new Date().toISOString().split("T")[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success("Snapshot exported as text file");
    } catch (error) {
      toast.error("Failed to export snapshot");
      console.error("Export error:", error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportMarkdown = async () => {
    setIsExporting(true);
    try {
      const date = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      
      const lines: string[] = [];
      lines.push(`# Phase Snapshot`);
      lines.push(`**${projectName}**`);
      lines.push(`*Exported on ${date}*`);
      lines.push("");
      lines.push("---");
      lines.push("");

      phases.forEach((phaseData) => {
        if (!phaseData.hasContent) return;

        const phaseLabel = PHASE_LABELS[phaseData.phase as Phase] || phaseData.phase;
        lines.push(`## ${phaseLabel}`);
        lines.push("");

        phaseData.blocks.forEach((block) => {
          lines.push(`### ${block.label}`);
          lines.push("");
          
          const items = block.structuredContent?.items || [];
          
          switch (block.contentType) {
            case "numbered-list":
              items.forEach((item, idx) => {
                lines.push(`${idx + 1}. ${item.value}`);
              });
              break;
              
            case "key-value":
              items.forEach((item) => {
                lines.push(`**${item.label}:** ${item.value}`);
                lines.push("");
              });
              break;
              
            case "offer-stack":
              items.forEach((item, idx) => {
                if (idx > 0) lines.push("---");
                lines.push(`**${item.label}**`);
                if (item.value) lines.push(item.value);
                if (item.secondary) lines.push(`*${item.secondary}*`);
                lines.push("");
              });
              break;
              
            case "checklist":
              items.forEach((item) => {
                lines.push(`- [x] ${item.value}`);
              });
              break;
              
            case "dates":
              lines.push("| Date | Value |");
              lines.push("|------|-------|");
              items.forEach((item) => {
                lines.push(`| ${item.label} | ${item.value} |`);
              });
              break;
              
            case "metrics":
              lines.push("| Metric | Value |");
              lines.push("|--------|-------|");
              items.forEach((item) => {
                lines.push(`| ${item.label} | ${item.value} |`);
              });
              break;
              
            case "quote":
              items.forEach((item) => {
                lines.push(`> "${item.value}"`);
              });
              break;
              
            case "social-bio":
              items.forEach((item) => {
                lines.push(`**${item.label}**`);
                lines.push(item.value);
                lines.push("");
              });
              break;
              
            case "badge":
              items.forEach((item) => {
                lines.push(`\`${item.value}\``);
              });
              break;
              
            default:
              items.forEach((item) => {
                lines.push(item.value);
              });
          }
          
          lines.push("");
        });
      });

      lines.push("---");
      lines.push("*Generated by Launchbox*");

      const content = lines.join("\n");
      const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `phase-snapshot-${new Date().toISOString().split("T")[0]}.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success("Snapshot exported as Markdown file");
    } catch (error) {
      toast.error("Failed to export snapshot");
      console.error("Export error:", error);
    } finally {
      setIsExporting(false);
    }
  };

  const hasContent = phases.some((p) => p.hasContent);

  if (!hasContent) {
    return null;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          disabled={isExporting}
          className="gap-2"
        >
          <Download className="w-4 h-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleExportText} className="gap-2 cursor-pointer">
          <FileText className="w-4 h-4" />
          Export as Text (.txt)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportMarkdown} className="gap-2 cursor-pointer">
          <File className="w-4 h-4" />
          Export as Markdown (.md)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
