// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's launch projects (id, name, status, active phase, launch date).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max number of projects to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("projects").select("id, name, description, status, active_phase, selected_funnel_type, launch_date, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's tasks. Optionally filter by project_id or by due date range.",
  inputSchema: {
    project_id: z2.string().uuid().optional().describe("Only return tasks for this project."),
    due_from: z2.string().optional().describe("ISO date (YYYY-MM-DD) inclusive lower bound on due_date."),
    due_to: z2.string().optional().describe("ISO date (YYYY-MM-DD) inclusive upper bound on due_date."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max tasks to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, due_from, due_to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("tasks").select("id, project_id, title, description, due_date, due_at, start_at, end_at, phase, category, priority, column_id, task_type").order("due_at", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (project_id) query = query.eq("project_id", project_id);
    if (due_from) query = query.gte("due_date", due_from);
    if (due_to) query = query.lte("due_date", due_to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool3({
  name: "create_task",
  title: "Create task",
  description: "Create a new task in the signed-in user's planner. Optionally attach to a project and set a due date.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Task title."),
    description: z3.string().optional().describe("Optional task description / notes."),
    project_id: z3.string().uuid().optional().describe("Attach the task to this project (must belong to the user)."),
    due_date: z3.string().optional().describe("Due date as YYYY-MM-DD."),
    priority: z3.enum(["low", "medium", "high"]).optional().describe("Task priority."),
    category: z3.string().optional().describe("Free-form category label.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, project_id, due_date, priority, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      project_id: project_id ?? null,
      due_date: due_date ?? null,
      priority: priority ?? null,
      category: category ?? "general",
      task_origin: "user",
      task_scope: "planner",
      task_type: "task",
      column_id: "todo"
    };
    const { data, error } = await supabaseForUser3(ctx).from("tasks").insert(payload).select("id, title, project_id, due_date, priority, category").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created task ${data.id}: ${data.title}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ydhagqgurqhlguxkkppb";
var mcp_default = defineMcp({
  name: "launchely-mcp",
  title: "Launchely",
  version: "0.1.0",
  instructions: "Tools for the Launchely / Cre8Visions launch platform. Use list_projects to see the user's launch projects, list_tasks to browse planner tasks, and create_task to add a new task.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_tasks_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
